// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AbstractDevice is an autogenerated mock type for the AbstractDevice type
type AbstractDevice struct {
	mock.Mock
}

// GetAddress provides a mock function with no fields
func (_m *AbstractDevice) GetAddress() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAddress")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetHostname provides a mock function with no fields
func (_m *AbstractDevice) GetHostname() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHostname")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetInterfaces provides a mock function with no fields
func (_m *AbstractDevice) GetInterfaces() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInterfaces")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLLDPNeigbours provides a mock function with no fields
func (_m *AbstractDevice) GetLLDPNeigbours() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLLDPNeigbours")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetStatus provides a mock function with no fields
func (_m *AbstractDevice) GetStatus() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetVendor provides a mock function with no fields
func (_m *AbstractDevice) GetVendor() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVendor")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Ping provides a mock function with no fields
func (_m *AbstractDevice) Ping() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetInterfaceDescription provides a mock function with no fields
func (_m *AbstractDevice) SetInterfaceDescription() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SetInterfaceDescription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetStatus provides a mock function with given fields: s
func (_m *AbstractDevice) SetStatus(s bool) {
	_m.Called(s)
}

// ShowDeviceInfo provides a mock function with no fields
func (_m *AbstractDevice) ShowDeviceInfo() {
	_m.Called()
}

// ShowInterfaces provides a mock function with no fields
func (_m *AbstractDevice) ShowInterfaces() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShowInterfaces")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// NewAbstractDevice creates a new instance of AbstractDevice. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAbstractDevice(t interface {
	mock.TestingT
	Cleanup(func())
}) *AbstractDevice {
	mock := &AbstractDevice{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
