networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1

  r1r2_net:
    name: r1r2_net
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.0.1.0/24

  r1r3_net:
    name: r1r3_net
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.0.2.0/24

  r2r3_net:
    name: r2r3_net
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.0.3.0/24

x-frr-defaults: &frr-defaults
  image: frrouting/frr:v8.4.1
  privileged: true
  networks:
    default: {}
  cap_add:
    - NET_ADMIN
    - SYS_ADMIN
  sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv4.conf.all.forwarding=1
    - net.ipv6.conf.all.forwarding=1
  tty: true
  command: >
    sh -c "apk add --no-cache openssh sudo &&
           echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config &&
           echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config &&
           echo 'root:frr' | chpasswd &&
           adduser -h /home/annet -s /bin/sh -D annet &&
           echo 'annet ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers &&
           echo -n 'annet:annet' | chpasswd &&
           ssh-keygen -A &&
           /usr/sbin/sshd &&
           /sbin/tini -- /usr/lib/frr/docker-start"

services:
  netbox:
    container_name: netbox
    hostname: netbox
    ports:
      - 8000:8080
    volumes:
      - ../topologies/lab01_basic_frr/src/:/home/ubuntu/src

  annet:
    container_name: annet
    hostname: annet
    image: annet
    volumes:
      - ../annet/config.yaml:/config.yaml
      - ../topologies/lab01_basic_frr/src/lab_generators:/lab_generators

  frr-r1:
    <<: *frr-defaults
    container_name: frr-r1
    hostname: frr-r1
    networks:
      default:
        ipv4_address: 172.20.0.111
      r1r2_net:
        ipv4_address: 10.0.1.12
      r1r3_net:
        ipv4_address: 10.0.2.13
    volumes:
      - ../topologies/lab01_basic_frr/operational_configs/frr-r1.frr/frr.conf:/etc/frr/frr.conf
      - ../topologies/common_configs/frr_common_daemons:/etc/frr/daemons:ro
      - ../topologies/common_configs/frr_common_vtysh:/etc/frr/vtysh.conf:ro

  frr-r2:
    <<: *frr-defaults
    container_name: frr-r2
    hostname: frr-r2
    networks:
      default:
        ipv4_address: 172.20.0.112
      r1r2_net:
        ipv4_address: 10.0.1.21
      r2r3_net:
        ipv4_address: 10.0.3.23
    volumes:
      - ../topologies/lab01_basic_frr/operational_configs/frr-r2.frr/frr.conf:/etc/frr/frr.conf
      - ../topologies/common_configs/frr_common_daemons:/etc/frr/daemons:ro
      - ../topologies/common_configs/frr_common_vtysh:/etc/frr/vtysh.conf:ro

  frr-r3:
    <<: *frr-defaults
    container_name: frr-r3
    hostname: frr-r3
    networks:
      default:
        ipv4_address: 172.20.0.113
      r1r3_net:
        ipv4_address: 10.0.2.31
      r2r3_net:
        ipv4_address: 10.0.3.32
    volumes:
      - ../topologies/lab01_basic_frr/operational_configs/frr-r3.frr/frr.conf:/etc/frr/frr.conf
      - ../topologies/common_configs/frr_common_daemons:/etc/frr/daemons:ro
      - ../topologies/common_configs/frr_common_vtysh:/etc/frr/vtysh.conf:ro
